// Skill collections registry - add your curated collections here
export const collections = [
  {
    id: "marketing",
    name: "Marketing Skills",
    author: "coreyhaines31",
    repo: "coreyhaines31/marketingskills",
    description: "33 marketing skills for copywriting, SEO, CRO, email, ads, pricing, and more.",
    count: 33,
    tags: ["marketing", "seo", "copywriting", "cro", "email", "ads"],
    skills: [
      { name: "ab-test-setup", description: "Design and implement A/B tests with proper sample sizes" },
      { name: "ad-creative", description: "Create ad copy and creatives for paid campaigns" },
      { name: "ai-seo", description: "Optimize content for AI-powered search engines" },
      { name: "analytics-tracking", description: "Set up GA4, GTM, and event tracking" },
      { name: "churn-prevention", description: "Reduce churn with dunning and cancel flow strategies" },
      { name: "cold-email", description: "Write cold outreach emails with follow-up sequences" },
      { name: "competitor-alternatives", description: "Create competitor comparison and alternative pages" },
      { name: "content-strategy", description: "Plan and execute content marketing strategies" },
      { name: "copy-editing", description: "Edit copy for clarity using plain English" },
      { name: "copywriting", description: "Write persuasive copy using proven frameworks" },
      { name: "email-sequence", description: "Build automated email sequences for every stage" },
      { name: "form-cro", description: "Optimize forms for higher conversion rates" },
      { name: "free-tool-strategy", description: "Plan free tools that drive signups and traffic" },
      { name: "launch-strategy", description: "Plan and execute product launches" },
      { name: "lead-magnets", description: "Create lead magnets that convert" },
      { name: "marketing-ideas", description: "Generate marketing ideas by category" },
      { name: "marketing-psychology", description: "Apply psychology principles to marketing" },
      { name: "onboarding-cro", description: "Optimize user onboarding flows" },
      { name: "page-cro", description: "Run conversion experiments on landing pages" },
      { name: "paid-ads", description: "Set up and optimize paid ad campaigns" },
      { name: "paywall-upgrade-cro", description: "Optimize paywall and upgrade flows" },
      { name: "popup-cro", description: "Design high-converting popups" },
      { name: "pricing-strategy", description: "Research and structure pricing tiers" },
      { name: "product-marketing-context", description: "Build product marketing positioning" },
      { name: "programmatic-seo", description: "Create programmatic SEO page strategies" },
      { name: "referral-program", description: "Design referral and affiliate programs" },
      { name: "revops", description: "Set up lead scoring, routing, and automation" },
      { name: "sales-enablement", description: "Create sales decks, one-pagers, and demo scripts" },
      { name: "schema-markup", description: "Add structured data markup for rich results" },
      { name: "seo-audit", description: "Audit sites for SEO issues and AI content detection" },
      { name: "signup-flow-cro", description: "Optimize signup flows for conversion" },
      { name: "site-architecture", description: "Plan site structure and navigation" },
      { name: "social-content", description: "Create platform-specific social media content" },
    ],
  },
];
